name: projectsub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  speech_to_text: ^7.0.0
  provider: ^6.1.2
  dart_openai: ^5.1.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  permission_handler: ^11.4.0

  date_time_format: ^2.0.1
  intl: ^0.20.2
#  flutter_tts: ^4.2.2
  flutter_tts: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true